version: '3.8'
services:
  superheros_backend:
    container_name: superheros_backend
    image: superheros_backend:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    env_file:
      - .env.dist
    ports:
      - ${PORT}:${PORT}
      - 3001:9229
    networks:
      - nesjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - nesjs-network
    restart: always
networks:
    nesjs-network:
      driver: bridge